'The cat screamed in defiance',
'Shadows danced all afternoon',
'You can be most anything',
'The Night’s Watch suck at watching',
'A risk was calculated',
'I met a squid yesterday',
'Her name is Princess Kitty',
'Cofounder of Kickstarter',
'I want a painting by you',
'I want to write a story',
'Will you come sit next to me?',
'I haven’t bathed in a week',
'Don’t pretend you don’t notice',
'I absolutely can’t wait',
'Don’t forget to love yourself',
'Charlatans, the whole damn lot',
'What a bunch of bologna', 
'The dogs pant incessantly', 
'Disney-branded hooligans',
'The dog looked back with contempt',
'Snow-covered biotech drones',
'Shake the dice and steal the rice',
'Banana-split disaster',
'You the plug or the outlet?',
'U up bro? It’s me, ya boy',
'Not everyone’s a poet',
'Dismantle white supremacy',
'Mmm mmm mmm mmm, that’s tasty',
'Dog-like robots kill us all',
'The boss and the assistant',
'Come up and see me sometime',
'The art on my walls is bad',
'You’re just a hot mess of lies',
'Extinction-level preschool',
'Post-apocalyptic vibe',
'Edgelords say: “Thanos was right”',
'Piano keys, melodies',
'Send me the link to your blog',
'Coconut water, a scam',
'Sunday morning hangover',
'I got you a kimono',
'Let’s open the kimono',
'What lies beneath my bathrobe',
'Booty-shakin’, earth-quakin’',
'So, what color handkerchief?',
'Are you friends with Dorothy?',
'The house smells like chicken fries',
'Kiss my shiny metal ass',
'Shut up and take my money',
'Terrycloth is for losers'